# .github/workflows/gcp-auth.yml

name: 'Authenticate to Google Cloud'

# Run this workflow when changes are pushed to the main branch
on:
  push:
    branches:
      - 'main'
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # These permissions are required for the OIDC token exchange
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
        
      - name: 'Authenticate to Google Cloud'
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          # UPDATE THIS LINE with your new Pool and Provider ID
          workload_identity_provider: 'projects/1030455078468/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider'
          
          # UPDATE THIS LINE with your new Service Account email
          service_account: 'github-folks-invoicez@thermal-origin-462809-t2.iam.gserviceaccount.com'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Verify authentication'
        run: |-
          echo "Successfully authenticated to Google Cloud."
          gcloud auth list
          echo "----------------------------------------"
          echo "Current GCP Project:"
          gcloud config list project

      # Add your GCP commands here
      # For example, listing Cloud Storage buckets
      - name: 'Example: List GCS Buckets'
        run: 'gcloud storage ls'
