# .github/workflows/gcp-auth.yml

name: 'Authenticate to Google Cloud'

# Run this workflow when changes are pushed to the main branch
on:
  push:
    branches:
      - 'main'
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # These permissions are required for the OIDC token exchange
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4

      - name: 'Authenticate to Google Cloud'
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          # This is the full resource name of your Workload Identity Pool Provider
          workload_identity_provider: 'projects/462809/locations/global/workloadIdentityPools/github-invoicez-deploy/providers/github'
          # This is the email of the service account to impersonate
          service_account: 'folks-938@thermal-origin-462809-t2.iam.gserviceaccount.com'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Verify authentication'
        run: |-
          echo "Successfully authenticated to Google Cloud."
          gcloud auth list
          echo "----------------------------------------"
          echo "Current GCP Project:"
          gcloud config list project

      # Add your GCP commands here
      # For example, listing Cloud Storage buckets
      - name: 'Example: List GCS Buckets'
        run: 'gcloud storage ls'
